# Generated by Django 3.1.7 on 2021-05-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postentry',
            name='author',
            field=models.CharField(max_length=180),
        ),
    ]
